### ISSUE TITLE
Link to binder on learn platform gives 404

### ISSUE THREAD

**Issue by domzae** [lewagon/python-scraping-workshop#2]
The binder link on the learn platform gives a 404:
[https://mybinder.org/v2/gh/lewagon/python-scraping-workshop/master?filepath=challenges.ipynb](https://mybinder.org/v2/gh/lewagon/python-scraping-workshop/master?filepath=challenges.ipynb)
it seems like the problem is with the linking directly to the notebook `?filepath=challenges.ipynb`
as [https://mybinder.org/v2/gh/lewagon/python-scraping-workshop/master](https://mybinder.org/v2/gh/lewagon/python-scraping-workshop/master) works fine.

**Comment by ssaunier** [comment]
Just tested, clicked on the first link and it opens properly in the latest version of mybinder 👇 

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/414418/214488667-7a29d7a3-c0d2-4d17-8f67-873376e02708.png">

✔️ Closing, thanks for reporting!
